version: '3.5'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodesanguedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: apihemo

  spring1:
    depends_on:
      - db
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: apihemo
      DB_NAME: bancodesanguedb
  spring2:
    depends_on:
      - db
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: apihemo
      DB_NAME: bancodesanguedb
  loadbalance:
    depends_on:
      - spring1
      - spring2
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]